#!/usr/bin/env python3
"""Create a fixture manifest after building the owned .NET IL demo.

Usage:
  dotnet build -c Release
  python create_manifest.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DLLS = sorted(ROOT.glob("bin/Release/*/GateDemo.dll")) or sorted(ROOT.glob("bin/Debug/*/GateDemo.dll"))
if not DLLS:
    raise SystemExit("GateDemo.dll not found. Run: dotnet build -c Release")

assembly = DLLS[-1]
sha = hashlib.sha256(assembly.read_bytes()).hexdigest()
manifest = {
    "name": "owned-dotnet-il-gate-demo",
    "description": "Owned/generated .NET IL gate fixture for solver and dry-run patch-plan regression tests.",
    "authorization": "Owned/generated by the researcher for this project. No third-party commercial code.",
    "allow_solve": True,
    "allow_patch_write": False,
    "notes": "Patch mode is dry-run only in the public tool. This manifest documents authorized lab analysis.",
    "targets": [
        {
            "role": "assembly",
            "path": str(assembly.relative_to(ROOT)).replace("\\", "/"),
            "sha256": sha,
        }
    ],
}
out = ROOT / "fixture.manifest.json"
out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
print(f"wrote {out}")
print(f"assembly: {assembly}")
print(f"sha256  : {sha}")
